[workspace]
authors = ["Michael Tran <michaelcao-anh.tran@uhn.ca>"]
channels = ["conda-forge", "bioconda"]
name = "cpg0016-emb-pipeline"
platforms = ["osx-arm64", "linux-64"]
version = "2.0.0"

[tasks]
qc = "Rscript -e \"rmarkdown::render('qc/cpg0016_emb_qc.Rmd', output_dir = 'qc', knit_root_dir = getwd())\""

[dependencies]
ruff = ">=0.15.5,<0.16"
python = ">=3.14.3,<3.15"
duckdb = ">=1.5.0,<2"
r-base = ">=4.5,<4.6"
r-arrow = "*"
bioconductor-multiassayexperiment = "*"
bioconductor-summarizedexperiment = "*"
bioconductor-s4vectors = "*"
pandoc = "*"
r-httr2 = "*"
r-knitr = "*"
r-rmarkdown = "*"
r-scales = "*"
r-yaml = "*"
ty = ">=0.0.24,<0.0.25"
r-uwot = ">=0.2.3,<0.3"
r-tidyverse = ">=2.0.0,<3"

[pypi-dependencies]
snakemake = ">=9.17.1, <10"
polars = ">=1.39.0, <2"
awscli = ">=1.42.8, <2"
air-formatter = "*"
